"""
IGES Exporter
Exports 3D models to IGES (Initial Graphics Exchange Specification) format
Compatible with: ANSYS, Abaqus, NASTRAN, and most CAD/CAE software
"""

import numpy as np
import logging
from typing import Dict, List
from datetime import datetime
import trimesh

logger = logging.getLogger(__name__)


class IGESExporter:
    """Exporter for IGES format"""

    def __init__(self):
        self.parameter_line_count = 0
        self.directory_entries = []
        self.parameter_data = []

    def export(self, model_data: Dict, filepath: str, options: Dict = None):
        """
        Export 3D model to IGES format

        Args:
            model_data: 3D model data from ModelGenerator
            filepath: Output file path
            options: Export options
                - units: Unit system (1=inches, 2=mm, 6=m)
                - description: Model description
                - author: Author name

        Note: This is a simplified IGES exporter focusing on mesh data.
        For complex surfaces, consider using specialized CAD libraries.
        """
        options = options or {}

        logger.info(f"Exporting to IGES: {filepath}")

        try:
            self.parameter_line_count = 0
            self.directory_entries = []
            self.parameter_data = []

            # Get model data
            vertices = np.array(model_data.get('vertices', []))
            faces = np.array(model_data.get('faces', []))

            if len(vertices) == 0 or len(faces) == 0:
                logger.warning("No geometry to export")
                return

            # Build IGES entities
            self._build_mesh_entities(vertices, faces)

            # Write IGES file
            with open(filepath, 'w') as f:
                self._write_start_section(f, options)
                self._write_global_section(f, options)
                self._write_directory_section(f)
                self._write_parameter_section(f)
                self._write_terminate_section(f)

            logger.info(f"IGES export successful: {filepath}")

        except Exception as e:
            logger.error(f"IGES export failed: {str(e)}")

            # Fallback to STL
            try:
                logger.info("Attempting fallback export via STL...")
                mesh = trimesh.Trimesh(vertices=vertices, faces=faces)
                stl_path = filepath.replace('.iges', '.stl').replace('.igs', '.stl')
                mesh.export(stl_path, file_type='stl')
                logger.warning(f"IGES export failed, created STL instead: {stl_path}")
            except Exception as e2:
                logger.error(f"Fallback export also failed: {str(e2)}")
                raise

    def _write_start_section(self, f, options: Dict):
        """Write Start section"""
        description = options.get('description', '2D to 3D Converted Model')
        author = options.get('author', 'Claude AI')

        start_lines = [
            f"2D to 3D Converter - {description}",
            f"Generated by: 2D to 3D Converter v1.0",
            f"Author: {author}",
            f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        ]

        for i, line in enumerate(start_lines, 1):
            # Start section: 72 chars + S + sequence number
            f.write(f"{line:<72}S{i:7d}\n")

    def _write_global_section(self, f, options: Dict):
        """Write Global section"""
        units = options.get('units', 2)  # 2 = millimeters

        # IGES global parameters
        global_params = [
            "1H,,",  # Parameter delimiter, record delimiter
            "1H;,",  # Product ID from sender
            f"25H2D to 3D Converter v1.0,",  # File name
            "24H2D to 3D Converter v1.0,",  # Native system ID
            "16H2D to 3D Converter,",  # Preprocessor version
            "32,",  # Number of binary bits for integers
            "38,",  # Single precision magnitude
            "308,",  # Single precision significance
            "308,",  # Double precision magnitude
            "15,",  # Double precision significance
            f"25H{options.get('description', 'Model')},",  # Product ID for receiver
            "1.0,",  # Model space scale
            f"{units},",  # Unit flag (2=mm)
            "1HM,",  # Units name
            "1,",  # Maximum line weight gradations
            "1.0,",  # Width of maximum line weight
            f"15H{datetime.now().strftime('%Y%m%d.%H%M%S')},",  # Date/time
            "0.001,",  # Minimum resolution
            "1000.0,",  # Approximate maximum coordinate
            f"10H{options.get('author', 'Claude')},",  # Author
            "0H,",  # Author's organization
            "11,",  # IGES version
            "0,",  # Drafting standard
            f"15H{datetime.now().strftime('%Y%m%d.%H%M%S')};",  # Model creation date
        ]

        # Write global section (each line up to 72 chars)
        line_num = 1
        current_line = ""

        for param in global_params:
            if len(current_line) + len(param) > 72:
                # Write current line and start new one
                f.write(f"{current_line:<72}G{line_num:7d}\n")
                line_num += 1
                current_line = param
            else:
                current_line += param

        # Write last line
        if current_line:
            f.write(f"{current_line:<72}G{line_num:7d}\n")

    def _build_mesh_entities(self, vertices: np.ndarray, faces: np.ndarray):
        """Build IGES entities for mesh"""
        # For each face, create a rational B-spline surface (Type 128) or
        # simpler: create vertex list (Type 502) and face list (Type 510)

        # Create vertex list entity (Type 502)
        vertex_entity = self._create_vertex_list(vertices)
        self.directory_entries.append(vertex_entity['directory'])
        self.parameter_data.append(vertex_entity['parameter'])

        # Create face entities for each triangle (Type 510)
        for face_idx, face in enumerate(faces):
            face_entity = self._create_face_entity(face, len(self.directory_entries) * 2 - 1)
            self.directory_entries.append(face_entity['directory'])
            self.parameter_data.append(face_entity['parameter'])

    def _create_vertex_list(self, vertices: np.ndarray) -> Dict:
        """Create IGES Vertex List entity (Type 502)"""
        param_lines = []

        # Entity type, number of vertices
        param_lines.append(f"502,{len(vertices)},")

        # Vertex coordinates
        for i, v in enumerate(vertices):
            param_lines.append(f"{v[0]:.6f},{v[1]:.6f},{v[2]:.6f},")

        # Remove trailing comma
        param_lines[-1] = param_lines[-1].rstrip(',') + ';'

        # Directory entry (2 lines)
        self.parameter_line_count += 1
        param_ptr = self.parameter_line_count

        directory = [
            f"     502       {param_ptr:7d}       0       0       0       0       0       000000001D      1",
            f"     502       0       0       1       0                               0D      2"
        ]

        return {
            'directory': directory,
            'parameter': param_lines
        }

    def _create_face_entity(self, face: np.ndarray, vertex_list_de: int) -> Dict:
        """Create IGES Face entity (Type 510)"""
        param_lines = []

        # Entity type, surface DE (0 for mesh), N (0), OF (outer loop flag), n (number of loops)
        param_lines.append(f"510,0,0,1,1,")

        # Loop: number of edges
        param_lines.append(f"{len(face)},")

        # Edge list (vertex indices, 1-based)
        for i in range(len(face)):
            v1 = face[i] + 1  # 1-based indexing
            v2 = face[(i + 1) % len(face)] + 1
            # Edge: vertex list DE, vertex1 index, vertex2 index
            param_lines.append(f"{vertex_list_de},{v1},{v2},")

        # Remove trailing comma
        param_lines[-1] = param_lines[-1].rstrip(',') + ';'

        # Directory entry
        self.parameter_line_count += 1
        param_ptr = self.parameter_line_count

        directory = [
            f"     510       {param_ptr:7d}       0       0       0       0       0       000000001D{len(self.directory_entries)*2+1:7d}",
            f"     510       0       0       1       0                               0D{len(self.directory_entries)*2+2:7d}"
        ]

        return {
            'directory': directory,
            'parameter': param_lines
        }

    def _write_directory_section(self, f):
        """Write Directory Entry section"""
        for entry in self.directory_entries:
            for line in entry:
                f.write(f"{line}\n")

    def _write_parameter_section(self, f):
        """Write Parameter Data section"""
        seq_num = 1

        for param_list in self.parameter_data:
            current_line = ""

            for param in param_list:
                if len(current_line) + len(param) > 64:
                    # Write current line
                    f.write(f"{current_line:<64} {seq_num:7d}P{seq_num:7d}\n")
                    seq_num += 1
                    current_line = param
                else:
                    current_line += param

            # Write remaining
            if current_line:
                f.write(f"{current_line:<64} {seq_num:7d}P{seq_num:7d}\n")
                seq_num += 1

    def _write_terminate_section(self, f):
        """Write Terminate section"""
        s_count = 4  # Number of Start section lines
        g_count = len([1 for line in open(f.name) if 'G' in line[-9:]])
        d_count = len(self.directory_entries) * 2
        p_count = self.parameter_line_count

        f.write(f"S{s_count:7d}G{g_count:7d}D{d_count:7d}P{p_count:7d}                                        T      1\n")


# For production use with complex surfaces, consider specialized libraries:
"""
Example using pyiges or other IGES libraries:

from pyiges import IGESModel

def export_with_pyiges(model_data, filepath):
    model = IGESModel()

    vertices = model_data['vertices']
    faces = model_data['faces']

    # Add vertices and faces to model
    for face in faces:
        pts = [vertices[i] for i in face]
        model.add_face(pts)

    model.save(filepath)
"""
